# Generated by Django 2.1 on 2022-10-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Port',
            new_name='Post',
        ),
    ]
