# Generated by Django 2.1 on 2022-10-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20221004_0922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='info',
        ),
    ]
